todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
    path('users/', include('users.urls')),
]

todo_app/urls.py
"""URL структура нашего приложения"""

from django.urls import path
from . import views


app_name="todo_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('lists/', views.lists, name='lists'),
    path('lists/<int:list_id>', views.list, name='list'),
    path('lists/del_completed/<int:list_id>', views.delete_completed, name='delete_completed'),
    path('lists/tasks/<int:task_id>', views.task_info, name='task_info'),
    path('lists/add_list', views.add_list, name='add_list'),
    path('lists/del_list/<int:list_id>', views.delete_list, name='delete_list'),
    path('lists/tasks/add_task/<int:list_id>', views.add_task, name='add_task'),
    path('lists/tasks/edit_task/<int:task_id>', views.edit_task, name='edit_task'),
    path('lists/tasks/del_task/<int:task_id>', views.delete_task, name='delete_task'),
    path('lists/tasks/status_invert/<int:task_id>', views.sts_invert, name="sts_invert"),
]

users/urls.py
"""Схема URL для пользователей"""
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class List(models.Model):
    """Класс, который описывает список дел"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date_opened = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    """Класс, который описывает конкретное дело в списке"""
    list = models.ForeignKey(List, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

todo_app/forms.py
from django import forms

from .models import List, Task


class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['name']
        labels = {'name': 'Название'}


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description']
        labels = {'name': 'Название', 'descriptioin': 'Описание'}

todo_app/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import List, Task
from .forms import ListForm, TaskForm


# Create your views here.
def index(request):
    """Домашняя страница"""
    return render(request, 'todo_app/index.html')


@login_required
def lists(request):
    """Страница со списком доступных списков дел"""
    users_lists = List.objects.filter(user=request.user).order_by('-date_opened')
    # расширенный список списков (добавилось количество невыполненных задач)
    extended_lists = []

    for list in users_lists:
        extended_lists.append({
            'name': list.name,
            'id': list.id,
            'tasks_count': list.task_set.filter(complete=False).count(),
        })
    context = {'lists': extended_lists}

    return render(request, 'todo_app/lists.html', context)


@login_required
def list(request, list_id):
    """Страница списка дел"""
    list = List.objects.get(id=list_id)
    check_list_owner(request.user, list)

    list.date_opened = datetime.now()
    list.save()
    tasks = list.task_set.order_by('complete', '-date_add')
    uc_count = tasks.filter(complete=False).count()
    context = {'list': list, 'tasks': tasks, 'count': uc_count}

    return render(request, 'todo_app/list.html', context)


@login_required
def task_info(request, task_id):
    """Страница с подробной информацией о задаче"""
    task = Task.objects.get(id=task_id)
    list = task.list
    check_list_owner(request.user, list)
    context = {'list': list, 'task': task}

    return render(request, 'todo_app/task_info.html', context)


@login_required
def add_list(request):
    """Форма создания списка"""

    if request.method != 'POST':
        form = ListForm()
    else:
        form = ListForm(data=request.POST)
        if form.is_valid():
            new_list = form.save(commit=False)
            new_list.user = request.user
            new_list.save()

            return redirect('todo_app:lists')

    context = {'form': form}
    return render(request, 'todo_app/new_list.html', context)


@login_required
def add_task(request, list_id):
    """Форма создания задачи"""
    list = List.objects.get(id=list_id)
    check_list_owner(request.user, list)

    if request.method != 'POST':
        form = TaskForm()
    else:
        form = TaskForm(data=request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.list = list
            new_task.save()

            return redirect('todo_app:list', list_id)

    context = {'list': list, 'form': form}
    return render(request, 'todo_app/new_task.html', context)


@login_required
def edit_task(request, task_id):
    """Форма для редактирования задачи"""
    task = Task.objects.get(id=task_id)
    list = task.list
    check_list_owner(request.user, list)

    if request.method != 'POST':
        form = TaskForm(instance=task)
    else:
        form = TaskForm(instance=task, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo_app:list', list.id)

    context = {'task': task, 'list': list, 'form': form}
    return render(request, 'todo_app/edit_task.html', context)


@login_required
def delete_task(request, task_id):
    """Удаление задачи"""
    task = Task.objects.get(id=task_id)
    list = task.list
    check_list_owner(request.user, list)

    task.delete()

    return redirect('todo_app:list', list.id)


@login_required
def delete_list(request, list_id):
    """Удаление списка"""
    list = List.objects.get(id=list_id)
    check_list_owner(request.user, list)

    list.delete()

    return redirect('todo_app:lists')


@login_required
def sts_invert(request, task_id):
    """Изменение статуса выполненности задачи"""
    task = Task.objects.get(id=task_id)
    list = task.list
    check_list_owner(request.user, list)

    # инвертирование значения
    task.complete = task.complete is not True
    task.save()

    return redirect('todo_app:list', list.id)


@login_required
def delete_completed(request, list_id):
    """Удаляет выполненные задачи"""
    list = List.objects.get(id=list_id)
    check_list_owner(request.user, list)

    list.task_set.filter(complete=True).delete()

    return redirect('todo_app:list', list_id)


def check_list_owner(user, list):
    """Проверка на владение списком"""
    if list.user != user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('todo_app:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

todo_app/templates/todo_app/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Список дел</title>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>


        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}

    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'todo_app:index' %}">
                ToDo Lists
            </a>
            <!--Раскрывающееся меню навигатсии для малых экранов-->
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo_app:lists' %}">
                            Мои списки
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Добрый день, {{ user.username }}!</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container ">
            <div class="pb-2 mb-2 border-bottom w-75 mr-auto ml-auto">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div class="w-75 mr-auto ml-auto">
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

todo_app/templates/todo_app/edit_task.html
{% extends 'todo_app/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h5>Назад к <a href="{% url 'todo_app:list' list.id %}">{{ list }}</a></h5>
  <h2>Измените задачу:</h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'todo_app:edit_task' task.id %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Cохранить</button>
    {% endbuttons %}
  </form>

{% endblock content %}

todo_app/templates/todo_app/index.html
{% extends "todo_app/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-4">Организуйте свои планы.</h1>

        <p class="lead">Создавайте свои списки с задачами! Будь-то список продуктов или планы на ближайщую неделю.
            Вы можете удобно делить дела по группам и отслеживать выполненные.
        </p>

        {% if user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'todo_app:lists' %}"
               role="button"> Начать &raquo;
            </a>
        {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
               role="button"> Начать &raquo;
            </a>
        {% endif %}
    </div>
{% endblock page_header %}

todo_app/templates/todo_app/list.html
{% extends 'todo_app/base.html' %}

{% block page_header %}
    <h3>{{ list }}</h3>
    <small><i>У вас {{ count }} невыполненн{{count|pluralize:"ая,ых" }} зада{{count|pluralize:"ча,ч"}}</i></small>
{% endblock page_header %}


{% block content %}
    <div class="mb-2">
        <a href="{% url 'todo_app:add_task' list.id %}" class="btn btn-primary">Создать новую задачу</a>
        <a href="{% url 'todo_app:delete_completed' list.id %}" class="btn btn-primary">Удалить выполненные</a>
    </div>
    <div class="list-group">
        {% for task in tasks %}
            {% if task.complete %}
            <div class="list-group-item-light list-group-item list-group-item-action text-center">
                <a href="{% url 'todo_app:sts_invert' task.id %}" class="status completed btn_link"></a>
                <a href="{% url 'todo_app:task_info' task.id %}" class="stretched-link text-decoration-none text-reset">
                    <del>{{ task }}</del>
                </a>
                <a href="{% url 'todo_app:delete_task' task.id%}" class="close btn_link" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </a>
                <a href="{% url 'todo_app:edit_task' task.id%}" class="mr-3 edit btn_link">
                    <span class="material-icons align-middle">edit</span>
                </a>

            </div>
            {% else %}
            <div class="list-group-item-primary list-group-item list-group-item-action text-center">
                <a href="{% url 'todo_app:sts_invert' task.id %}" class="status uncompleted btn_link"></a>
                <a href="{% url 'todo_app:task_info' task.id %}" class="stretched-link text-decoration-none text-reset">
                    {{ task }}
                </a>
                <a href="{% url 'todo_app:delete_task' task.id%}" class="close btn_link">
                  <span aria-hidden="true">&times;</span>
                </a>
                <a href="{% url 'todo_app:edit_task' task.id%}" class="mr-3 edit btn_link">
                    <span class="material-icons align-middle">edit</span>
                </a>

            </div>
            {% endif %}
        {% empty %}
            <p class="list-group-item">Вы ещё не создали ни одной задачи</p>
        {% endfor %}
    </div>

{% endblock content %}

todo_app/templates/todo_app/lists.html
{% extends 'todo_app/base.html' %}

{% block page_header %}
    <h2>Доступные списки дел:</h2>
{% endblock page_header %}

{% block content %}
    <div class="mb-2">
        <a href="{% url 'todo_app:add_list' %}" class="btn btn-primary">Создать новый список дел</a>
    </div>
    <div class="list-group">
        {% for list in lists %}
        <div class="list-group-item list-group-item-action">
            <a class="stretched-link text-decoration-none text-reset" href="{% url 'todo_app:list' list.id %}">
                {{ list.name }}
                {% if list.tasks_count > 0 %}
                    <span class="badge badge-primary badge-pill">{{ list.tasks_count }}</span>
                {% endif %}
            </a>
            <a href="{% url 'todo_app:delete_list' list.id %}" class="close btn_link" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
            </a>
        </div>
        {% empty %}
            <p class="list-group-item">Вы ещё не создали ни один список дел</p>
        {% endfor %}
    </div>


{% endblock content %}

todo_app/templates/todo_app/new_list.html
{% extends 'todo_app/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Создайте новый список дел:</h2>
{% endblock page_header %}

{% block content %}


  <form action="{% url 'todo_app:add_list' %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Создать список дел</button>
    {% endbuttons %}
  </form>

{% endblock content %}

todo_app/templates/todo_app/new_task.html
{% extends 'todo_app/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h5>Назад к <a href="{% url 'todo_app:list' list.id %}">{{ list }}</a></h5>
  <h2>Создайте новую задачу</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'todo_app:add_task' list.id %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Создать задачу</button>
    {% endbuttons %}
  </form>

{% endblock content %}

todo_app/templates/todo_app/task_info.html
{% extends 'todo_app/base.html' %}

{% block page_header %}
    <h5>Назад к <a href="{% url 'todo_app:list' list.id %}">{{ list }}</a></h5>
{% endblock page_header %}

{% block content %}

    <div class="card text-white bg-primary">
        <div class="card-header">
            <h4 class="card-title">{{ task.name }}</h4>
        </div>
        <div class="card-body">
            <p class="card-text">{{ task.description }}</p>
            {% if task.description != "" %}
                <hr>
            {% endif %}
            <h6 class="card-title">Создана:</h6>
            <p class="card-text">{{ task.date_add|date:'M d, Y H:i' }}</p>
        </div>
    </div>

{% endblock content %}